apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
data:
  ######
  # General Settings Values
  #
  # The following are Settings for the environment to bootstrap with
  #
  ######
  billing-id: "0000000000"
  org-id: "0000000000"
  department-code: "goc"
  ######
  #
  # Org Policies
  #
  ######
  allowed-images: |
    - "projects/debian-cloud"
    - "projects/cos-cloud"
  allowed-loadbalacers: |
    - INTERNAL
  allowed-domain-contacts: |
    - "@example.com"
  allowed-domain-members: |
    - "asdasda"
  can-ip-forward: | # organizations/ORGANIZATION_ID, folders/FOLDER_ID, projects/PROJECT_ID,  or projects/PROJECT_ID/zones/ZONE/instances/INSTANCE-NAME. 
   - "" 
  ######
  # Guardrails Values
  ######
  #
  # Required to be compliant with Guardrails 05 - Data Location
  # This will prevent resources from being provisioned outside of the lists regions. 
  # To be PBMM Compliant resources must be located in Canadian Regions
  # https://github.com/canada-ca/cloud-guardrails/blob/master/EN/05_Data-Location.md
  #
  allowed-regions: |
    - northamerica-northeast1
    - northamerica-northeast2
  # Required to be compliant with Guardrails 04 - Enterprise Monitoring
  # Create role-based account to enable enterprise monitoring and visibility
  # Emails used must be Already in Cloud Identity
  # Users and roles will be created for the accociated emails
  # https://github.com/canada-ca/cloud-guardrails/blob/master/EN/04_Enterprise-Monitoring-Accounts.md
  #
  ######
  asset-viewer-group: email@domain.com
  audit-data-group: email@domain.com
  audit-data-viewer-group: email@domain.com
  billing-data-group: email@domain.com
  billing-data-viewer-group: email@domain.com
  billing-console-viewer-group: email@domain.com
  ####
  # Guardrails Project Values
  guardrails-project-id: guardrails-00000 # Must be globally unique