apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
data:
  ######
  # General Settings Values
  ######
  allowed-regions: |
    - northamerica-northeast1
    - northamerica-northeast2
  asset-viewer-group: ssc-broker@chriscarty.altostrat.com
  audit-data-group: ssc-broker@chriscarty.altostrat.com
  audit-data-viewer-group: ssc-broker@chriscarty.altostrat.com 
  billing-data-group: ssc-broker@chriscarty.altostrat.com
  billing-data-viewer-group: ssc-broker@chriscarty.altostrat.com
  billing-console-viewer-group: ssc-broker@chriscarty.altostrat.com
  billing-id: "011F2A-8F38DD-24870A"
  org-id: "1020902403876"
  department-code: "goc"
  region: northamerica-northeast1
  region2: northamerica-northeast2
  ######
  # Protected B Project Values
  ######
  projected-b-project-name: protected-b-23123123
  ######
  # Unclassified Project Values
  ######
  unclassified-project-name: unclassified-23123123
  # Guardrails Project Values
  guardrails-project-id: guardrails-23123123 # Must be globally unique
  ######
  # GKE Sandbox Network Values
  ######
  routing-mode: REGIONAL # REGIONAL or GLOBAL
  mtu: 1460 # Range can be between 1460 and 1500 bytes
  subnet-cidr: 10.2.0.0/16
  log-aggregation-interval: INTERVAL_5_SEC # Possible Values ["INTERVAL_5_SEC", "INTERVAL_30_SEC", "INTERVAL_1_MIN", "INTERVAL_5_MIN", "INTERVAL_10_MIN", "INTERVAL_15_MIN"]
  flow-sampling: 0.5 # Value must be between 0 and 1
  log-metadata: INCLUDE_ALL_METADATA # Possible Values ["EXCLUDE_ALL_METADATA", "INCLUDE_ALL_METADATA", "CUSTOM_METADATA"]
  # log-metadatafields: | # Use if CUSTOM_METADATA is used for `log-metadata`
  #   - test 
  private-google-access: true
  gke-services-cidr: 10.3.0.0/16
  gke-pod-cidr: 10.4.0.0/16
  ######
  # Sandbox Cluster Values
  ######
  sandbox-project-id: sandbox-23123123 # Must be globally unique
  zone: northamerica-northeast1-a
  cluster-description: dev-cluster
  cluster-name: sandbox 
  auth-network: | 
    - cidrBlock: 35.237.129.190/32
      displayName: private-net
  labels:
    availability: test
    target-audience: test      
  tags: |
    - regional
    - northamerica
    - sandbox
  repo: https://github.com/cartyc/acm-test.git # Example repo replace with your own.
  branch: prod-env
  gke-admin: ssc-broker@chriscarty.altostrat.com
  gke-viewer: ssc-broker@chriscarty.altostrat.com
  machineType: e2-standard-8
