apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetworkPeering
metadata:
  name: public-networkpeerin
  namespace: common
spec:
  exportCustomRoutes: false
  importCustomRoutes: false
  networkRef:
    name: privperimvpc
  peerNetworkRef:
    name: computenetworkpeering-dep2
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    label-one: "value-one"
  name: pubperimvpc
  namespace: common
spec:
  description: The Public Perimeter VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false
  deleteDefaultRoutesOnCreate: true
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "value-one"
  name: public
  namespace: common
spec:
  ipCidrRange: 10.10.0.0/26
  region: northamerica-northeast1
  description: This subnet is used for the private interface of the fortigate firewall
  privateIpGoogleAccess: true
  networkRef:
    name: privperimvpc
  logConfig:
    aggregationInterval: INTERVAL_1_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA