apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/k8s-viewer
  name: k8s-viewer
  namespace: config-control # kpt-set: ${namespace}
spec:
  member: group:email@domain.com # kpt-set: group:${gke-viewer}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: sandbox # kpt-set: ${sandbox-project-id}
  role: roles/container.clusterViewer
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/k8s-admin
  name: k8s-admin
  namespace: config-control # kpt-set: ${namespace}
spec:
  member: group:email@domain.com # kpt-set: group:${gke-admin}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: sandbox # kpt-set: ${sandbox-project-id}
  role: roles/container.admin
