# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-net
  name: sandbox-net # kpt-set: ${cluster-name}-net
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL # kpt-set: ${routing-mode}
  mtu: 1460 # kpt-set: ${mtu}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-subnet
  name: sandbox-subnet # kpt-set: ${cluster-name}-subnet
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  ipCidrRange: 10.2.0.0/16 # kpt-set: ${subnet-cidr}
  networkRef:
    name: sandbox-net # kpt-set: ${cluster-name}-net
  region: northamerica-northeast1 # kpt-set: ${region}
  privateIpGoogleAccess: true # kpt-set: ${private-google-access}
  logConfig:
    aggregationInterval: INTERVAL_10_MIN # kpt-set: ${log-aggreation-interval}
    flowSampling: 0.5 # kpt-set: ${flow-sampling}
    metadata: INCLUDE_ALL_METADATA # kpt-set: ${log-metadata}
    metadataFields: # kpt-set: ${log-metadatafields}
      - ""
  secondaryIpRange:
    - ipCidrRange: 10.3.0.0/16 # kpt-set: ${gke-services-cidr}
      rangeName: servicesrange
    - ipCidrRange: 10.4.0.0/16 # kpt-set: ${gke-pod-cidr}
      rangeName: clusterrange
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata: # kpt-merge: ${NAMESPACE}/computerouternat-dep-forallsubnets
  name: router-sandbox-net # kpt-set: router-${cluster-name}-net
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  description: example router description
  networkRef:
    name: sandbox-net # kpt-set: ${cluster-name}-net
  region: northamerica-northeast1 # kpt-set: ${region}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata: # kpt-merge: ${NAMESPACE}/computerouternat-sample-forallsubnets
  name: nat-sandbox-net # kpt-set: nat-${cluster-name}-net
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  natIpAllocateOption: AUTO_ONLY
  region: northamerica-northeast1 # kpt-set: ${region}
  routerRef:
    name: router-sandbox-net # kpt-set: router-${cluster-name}-net
  sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
  subnetwork:
  - subnetworkRef:
      name: sandbox-subnet # kpt-set: ${cluster-name}-subnet
    sourceIpRangesToNat:
    - ALL_IP_RANGES
---
### Firewall Rules to comply with NIST
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata: # kpt-merge: config-control/nist-firewall-deny
  name: nist-firewall-deny
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: sandbox-00000 # kpt-set: ${sandbox-project-id}
spec:
  deny:
    - protocol: tcp
      ports:
        - "9090"
        - "7000-7001"
        - "7199"
        - "8888"
        - "9160"
        - "61620-61621"
        - "9200"
        - "9300"
        - "21"
        - "80"
        - "389"
        - "636"
        - "11211"
        - "11214-11215"
        - "27017-27019"
        - "3306"
        - "137-139"
        - "1521"
        - "2483-2484"
        - "110"
        - "5432"
        - "3389"
        - "6379"
        - "25"
        - "22"
        - "23"
    - protocol: udp
      ports:
        - "445"
        - "53"
        - "389"
        - "11211"
        - "11214-11215"
        - "137-139"
        - "2483-2484"
        - "5432"
        - "3389"
    - protocol: sctp
      ports:
        - "22"
  networkRef:
    name: sandbox-net # kpt-set: ${cluster-name}-net
