apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: testvpc
spec:
  description: The Non-Production Shared VPC
  routingMode: GLOBAL
  autoCreateSubnetworks: false
  mtu: 0
  deleteDefaultRoutesOnCreate: true
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  labels:
    label-one: "value-one"
  name: subnet01
spec:
  ipCidrRange: 10.10.20.0/24
  region: northamerica-northeast1
  description: This subnet has a description
  privateIpGoogleAccess: true
  networkRef:
    name: computesubnetwork-dep
  logConfig:
    aggregationInterval: INTERVAL_5_SEC
    flowSampling: 0.5
    metadata: "INCLUDE_ALL_METADATA"
---