  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeRoute
  metadata:
    name: egress-internet
  spec:
    description: "route through IGW to access internet"
    destRange: 0.0.0.0/0
    nextHopGateway: ""
    networkRef:
      name: testvpc
    priority: 0
    nextHopIp: ""
    nextHopInstanceRef:
    - external: name
    nextHopVPNTunnelRef:
    - external: name
    tags:
    - "egress-inet"
