apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata: # kpt-merge: ${NAMESPACE}/computerouternat-sample-forallsubnets
  name: nat-sandbox-net # kpt-set: nat-${cluster-name}-net
  namespace: sandbox # kpt-set: ${sandbox-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-project-id" # kpt-set: ${sandbox-project-id}  
spec:
  natIpAllocateOption: AUTO_ONLY
  region: us-central1 # kpt-set: ${region}
  routerRef:
    name: router-sandbox-net # kpt-set: router-${cluster-name}-net
  sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
  subnetwork:
  - subnetworkRef:
      name: sandbox-subnet # kpt-set: ${cluster-name}-subnet
    sourceIpRangesToNat:
    - ALL_IP_RANGES
