apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata: # kpt-merge: ${NAMESPACE}/gkehubfeature-acm
  name: anthos-config-management
  namespace: config-control # kpt-set: ${namespace}
  labels:
    feature: acm
  annotations:
    cnrm.cloud.google.com/project-id: sandbox-00000 # kpt-set: ${sandbox-project-id}
spec:
  location: global
  projectRef:
    name: sandbox
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-cluster
  name: sandbox-hub # kpt-set: ${cluster-name}-hub
  namespace: config-control # kpt-set: ${namespace}
  labels:
    label-one: value-one
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}
spec:
  description: sandbox # kpt-set: ${cluster-name}
  endpoint:
    gkeCluster:
      resourceRef:
        external: https://container.googleapis.com/v1/projects/sandbox-00000/locations/northamerica-northeast1-a/clusters/sandbox # kpt-set: https://container.googleapis.com/v1/projects/${sandbox-project-id}/locations/${zone}/clusters/${cluster-name}
  location: global
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata: # kpt-merge: ${NAMESPACE}/gkehub-${CLUSTER_NAME}
  name: gkehub-sandbox-features # kpt-set: gkehub-${cluster-name}
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  configmanagement:
    binauthz:
      enabled: true
    configSync:
      git:
        policyDir: ""
        secretType: "none"
        syncBranch: prod-env # kpt-set: ${branch}
        syncRepo: https://github.com/cartyc/acm-test.git # kpt-set: ${repo}
        syncRev: "HEAD"
        syncWaitSecs: "20"
      sourceFormat: hierarchy
    policyController:
      auditIntervalSeconds: "20"
      enabled: true
      exemptableNamespaces:
        - "config-management-system"
        - "falco-system"
        - "csi-driver"
      logDeniesEnabled: true
      referentialRulesEnabled: true
      templateLibraryInstalled: true
    version: 1.9.0
  featureRef:
    name: gkehubfeature-acm
  location: global
  membershipRef:
    name: sandbox-hub # kpt-set: ${cluster-name}-hub
  projectRef:
    external: sandbox-00000 # kpt-set: ${sandbox-project-id}
