#############
#
# Add exception to Org Policies for GKE
# If not the GKE cluster will fail to come online
#
#############
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: require-shielded-vm-false
spec:
  constraint: "constraints/compute.requireShieldedVm"
  booleanPolicy:
    enforced: false
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    name: "sandbox"
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: gke-restrict-ip-forwarding
spec:
  constraint: "constraints/compute.vmCanIpForward"
  list:
    values:
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    name: "sandbox"
