apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata: # kpt-merge: config-control/my-super-secret-secret
  name: my-super-secret-secret
  namespace: config-control # kpt-set: ${namespace}  
  labels:
    replication-type: user-managed
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox" # kpt-set: ${sandbox-project-id}
spec:
  replication:
    userManaged:
      replicas:
        - location: northamerica-northeast1
        - location: northamerica-northeast2
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata: # kpt-merge: config-control/secretmanagersecretversion-sample
  name: secretmanagersecretversion-sample
  namespace: config-control # kpt-set: ${namespace}
spec:
  secretRef:
    name: my-super-secret-secret
  enabled: true
  secretData:
    value: secret-squirel
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata: # kpt-merge: config-control/gke-workload
  name: gke-workload
  namespace: config-control # kpt-set: ${namespace}     
  labels:
    label-one: "value-one"
spec:
  displayName: gke-workload user
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/workloadid-user
  name: workloadid-user
  namespace: config-control # kpt-set: ${namespace}  
spec:
  member: serviceAccount:sandbox.svc.id.goog[secret-app/mypodserviceaccount] # kpt-set: serviceAccount:${sandbox-project-id}.svc.id.goog[secret-app/mypodserviceaccount]
  resourceRef:
    name: gke-workload@sandbox.iam.gserviceaccount.com # kpt-set: gke-workload@${sandbox-project-id}.iam.gserviceaccount.com
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  role: roles/iam.workloadIdentityUser
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/secret-user
  name: secret-user
  namespace: config-control # kpt-set: ${namespace}  
spec:
  member: serviceAccount:gke-workload@sandbox.iam.gserviceaccount.com # kpt-set: serviceAccount:gke-workload@${sandbox-project-id}.iam.gserviceaccount.com
  resourceRef:
    name: my-super-secret-secret
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
  role: roles/secretmanager.secretAccessor
