apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-worker-pool-1
  name: sandbox-worker-pool-1 # kpt-set: ${cluster-name}-worker-pool-1
  namespace: sandbox # kpt-set: ${sandbox-namespace}
  labels:
    cluster: sandbox # kpt-set: ${cluster-name}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-project-id" # kpt-set: ${sandbox-project-id}
    # config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespace/sandbox/containercluster/sandbox
spec:
  autoscaling:
    maxNodeCount: 3
    minNodeCount: 1
  clusterRef:
    name: sandbox # kpt-set: ${cluster-name}
  initialNodeCount: 3
  location: us-central1 # kpt-set: ${region}
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD
    machineType: e2-standard-4 # kpt-set: ${machineType}
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    preemptible: false
    tags: # kpt-set: ${tags}
      - regional
      - northamerica
      - sandbox
    metadata: {}
