apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-worker-pool-1
  name: sandbox-worker-pool-1 # kpt-set: ${cluster-name}-worker-pool-1
  namespace: config-control # kpt-set: ${namespace}
  labels:
    cluster: sandbox # kpt-set: ${cluster-name}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}
spec:
  autoscaling:
    maxNodeCount: 3
    minNodeCount: 1
  clusterRef:
    name: sandbox # kpt-set: ${cluster-name}
  initialNodeCount: 3
  location: northamerica-northeast1 # kpt-set: ${region}
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    metadata:
      disable-legacy-endpoints: "true"
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD
    machineType: e2-standard-8 # kpt-set: ${machineType}
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    preemptible: false
    tags: # kpt-set: ${tags}
      - regional
      - northamerica
      - sandbox