apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: ${NAMESPACE}/${CLUSTER_NAME}-bq-viewer
  name: gkemetering-bq-viewer
  namespace: config-control # kpt-set: ${namespace}
spec:
  # replace ${PROJECT_ID?} with your project name
  member: group:email@domain.com # kpt-set: group:${billing-data-viewer-group}
  role: roles/bigquery.dataViewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: sandbox # kpt-set: ${sandbox-project-id}