#########
#
# GCP Organization Policies
# Org policies that correspond with a Guardrail will container a label indicating what Guardrails it helps in enforcing
#
#########
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: restrict-resource-locations
  labels:
    guardrails-enforced: guardrail-05
spec:
  constraint: "constraints/gcp.resourceLocations"
  listPolicy:
    allow:
      all: true
      values: # kpt-set: ${allowed-regions}
        - northamerica-northeast1
        - northamerica-northeast2
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: disable-vpc-external-ipv6
  labels:
    guardrail-enforced: guardrail-09
spec:
  constraint: "constraints/compute.disableVpcExternalIpv6"
  booleanPolicy:
    enforced: true
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: require-shielded-vm
spec:
  constraint: "constraints/compute.requireShieldedVm"
  booleanPolicy:
    enforced: true
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: require-trusted-images
spec:
  constraint: "constraints/compute.trustedImageProjects"
  listPolicy:
    values:
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}   
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: restrict-vm-external-access
  labels:
    guardrail-enforced: guardrail-09  
spec:
  constraint: "constraints/compute.vmExternalIpAccess"
  list:
    values:
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}          
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: disable-serviceaccount-key-creation
spec:
  constraint: "constraints/iam.disableServiceAccountKeyCreation"
  booleanPolicy:
    enforced: true
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}              
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: restrict-vpc-peering
  labels:
    guardrail-enforced: guardrail-09  
spec:
  constraint: "constraints/compute.restrictVpcPeering"
  listPolicy:
    allow:
      all: true
      values:
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "0000000000" # kpt-set: ${org-id}       
