apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: ${guardrails-namespace}/kcc-${guardrails-project-id}-owners-permissions
  name: kcc-guardrails-00000-owners-permissions # kpt-set: kcc-${guardrails-project-id}-owners-permissions
  namespace: guardrails # kpt-set: ${guardrails-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: config-controller-project-id # kpt-set: ${management-project-id}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: guardrails-00000 # kpt-set: ${guardrails-project-id}
  bindings:
    - role: roles/owner
      members:
        - member: serviceAccount:guardrails-00000@config-controller-project-id.iam.gserviceaccount.com # kpt-set: serviceAccount:${guardrails-project-id}@${management-project-id}.iam.gserviceaccount.com
