#############
#
# Both of these policies need to be inplace
# If not the GKE cluster will fail to come online
#
#############
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata: # kpt-merge: /require-shielded-vm-false
  name: require-shielded-vm-false
spec:
  constraint: "constraints/compute.requireShieldedVm"
  booleanPolicy:
    enforced: false
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    name: "sandbox"
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata: # kpt-merge: /restrict-ip-forwarding
  name: restrict-ip-forwarding
spec:
  constraint: "constraints/compute.vmCanIpForward"
  list: {}
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    name: "sandbox"
