# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########
# BigQuery Log Sink
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata: # kpt-merge: guardrails/bigquery-logsink
  name: bigquery-logsink
  namespace: config-control # kpt-set: ${management-namespace}
spec:
  destination:
    bigQueryDatasetRef:
      name: bigquerylogginglogsink
      namespace: guardrails
  includeChildren: true
  filter: logName:cloudaudit.googleapis.com
  organizationRef:
    external: "0000000000" # kpt-set: ${org-id}
---
#########
# Big Query Instance
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata: # kpt-merge: guardrails/bigquerylogginglogsink
  name: bigquerylogginglogsink
  namespace: guardrails # kpt-set: ${guardrails-namespace}
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "true"
spec:
  location: northamerica-northeast1
  projectRef:
    external: project-id # kpt-set: ${guardrails-project-id}
---
# BigQuery Audit Log Viewer
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/bq-audit-data-viewer
  name: bq-sink-writer
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    config.kubernetes.io/apply-time-mutation: |
      - sourceRef:
          apiVersion: logging.cnrm.cloud.google.com/v1beta1
          kind: LoggingLogSink
          name: bigquery-logsink
        sourcePath: $.status.writerIdentity
        targetPath: $.spec.member
        token: ${logging-writerIdentity}
spec:
  member: ${logging-writerIdentity}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: project-id # kpt-set: ${guardrails-project-id}
  role: roles/bigquery.admin
