# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeVPNGateway
metadata:
  name: ha_gateway
  namespace: nonprod
spec:
  description: "Compute VPN Gateway Sample"
  region: us-central1
  networkRef:
    name: computevpngateway-dep
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeExternalVPNGateway
metadata:
  name: computeexternalvpngateway-sample
  namespace: nonprod
  labels:
    label-one: "value-one"
spec:
  description: an external vpn gateway
  redundancyType: "SINGLE_IP_INTERNALLY_REDUNDANT"
  interface:
    - id: 0
      ipAddress: "8.8.8.8"
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeVPNTunnel
metadata:
  name: computevpntunnel-sample
  namespace: nonprod
  labels:
    foo: bar
spec:
  peerIp: "15.0.0.120"
  region: us-central1
  sharedSecret:
    valueFrom:
      secretKeyRef:
        name: computevpntunnel-dep
        key: sharedSecret
  targetVPNGatewayRef:
    name: computevpntunnel-dep
  localTrafficSelector:
    - "192.168.0.0/16"
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterInterface
metadata:
  name: computerouterinterface-sample
  namespace: nonprod
spec:
  routerRef:
    name: computerouterinterface-dep
  region: us-central1
  ipRange: "169.254.1.1/30"
  vpnTunnelRef:
    name: computerouterinterface-dep
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterPeer
metadata:
  name: computerouterpeer-sample
  namespace: nonprod
spec:
  region: us-central1
  peerIpAddress: "169.254.0.2"
  peerAsn: 65513
  ipAddress:
    external: "169.254.0.1"
  advertisedRoutePriority: 1
  routerRef:
    name: computerouterpeer-dep
  routerInterfaceRef:
    name: computerouterpeer-dep    