# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#############
#
# Both of these policies need to be inplace
# If not the GKE cluster will fail to come online
#
#############
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: require-shielded-vm-false
  namespace: config-control # kpt-set: ${namespace}
spec:
  constraint: "constraints/compute.requireShieldedVm"
  booleanPolicy:
    enforced: false
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: sandbox-project-id # kpt-set: ${sandbox-project-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: restrict-ip-forwarding
  namespace: config-control # kpt-set: ${namespace}
spec:
  constraint: "constraints/compute.vmCanIpForward"
  listPolicy:
    allow:
      values:
        - "under:projects/sandbox-project-id" # kpt-set: under:projects/${sandbox-project-id}
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: sandbox-project-id # kpt-set: ${sandbox-project-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: require-os-login
  namespace: config-control # kpt-set: ${namespace}
spec:
  constraint: "constraints/compute.requireOsLogin"
  booleanPolicy:
    enforced: false
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: sandbox-project-id # kpt-set: ${sandbox-project-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: restrict-vpc-peering
  namespace: config-control # kpt-set: ${namespace}
spec:
  constraint: "constraints/compute.restrictVpcPeering"
  listPolicy:
    allow:
      all: true
  projectRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: sandbox-project-id # kpt-set: ${sandbox-project-id}    
