apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata: # kpt-merge: ${NAMESPACE}/gkehub-${CLUSTER_NAME}
  name: gkehub-sandbox # kpt-set: gkehub-${cluster-name}
  namespace: config-control # kpt-set: ${sandbox-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-00000" # kpt-set: ${sandbox-project-id}  
spec:
  configmanagement:
    binauthz:
      enabled: true
    configSync:
      git:
        policyDir: ""
        secretType: "none"
        syncBranch: prod-env # kpt-set: ${branch}
        syncRepo: https://github.com/cartyc/acm-test.git # kpt-set: ${repo}
        syncRev: "HEAD"
        syncWaitSecs: "20"
      sourceFormat: hierarchy
    policyController:
      auditIntervalSeconds: "20"
      enabled: true
      exemptableNamespaces:
        - "config-management-system"
        - "falco-system"
        - "csi-driver"
      logDeniesEnabled: true
      referentialRulesEnabled: true
      templateLibraryInstalled: true
    version: 1.9.1 # kpt-set: ${acm-version}
  featureRef:
    name: anthos-config-management
  location: global
  membershipRef:
    name: sandbox-hub # kpt-set: ${cluster-name}-hub
  projectRef:
    external: sandbox-00000 # kpt-set: ${sandbox-project-id}