# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: binaryauthorization.cnrm.cloud.google.com/v1beta1
kind: BinaryAuthorizationPolicy
metadata: # kpt-merge: config-control/binauth-allowed-repos
  name: binauth-allowed-repos
  namespace: sandbox # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: "sandbox-000000" # kpt-set: ${project-id}
    config.kubernetes.io/depends-on: serviceusage.cnrm.cloud.google.com/namespace/config-control/Service/binaryauthorization # kpt-set: resourcemanager.cnrm.cloud.google.com/namespace/${project-id}/Project/binaryauthorization,iam.cnrm.cloud.google.com/namespace/${project-namespace}/IAMPolicyMember/${project-id}-binauth-admin
spec:
  admissionWhitelistPatterns:
    - namePattern: "gcr.io/google_containers/*"
    - namePattern: "gcr.io/google-containers/*"
    - namePattern: "k8s.gcr.io/*"
    - namePattern: "gke.gcr.io/*"
    - namePattern: "gcr.io/stackdriver-agents/*"
    - namePattern: "gcr.io/google-samples/*"
    - namePattern: "northamerica-northeast1-docker.pkg.dev/sandbox-00000/container-registry" # kpt-set: ${region}-docker.pkg.dev/${project-id}/container-registry
  defaultAdmissionRule:
    enforcementMode: "ENFORCED_BLOCK_AND_AUDIT_LOG"
    evaluationMode: "ALWAYS_ALLOW"
  globalPolicyEvaluationMode: ENABLE
  projectRef:
    external: sandbox-000000 # kpt-set: ${project-id}
